checks:
    python:
        code_rating: true
        duplicate_code: true
tools:
    pylint:
        python_version: '3'
        config_file: .pylintrc
filter:
    excluded_paths:
        - '*/tests/*'
build:
    cache:
        directories:
            - ./lib/python3.5/site-packages
            - ~/.analysis
    environment:
        python: '3.5.0'
        variables:
            DJANGO_SETTINGS_MODULES: settings
            DATABASE_URL: postgres://scrutinizer:scrutinizer@localhost:5434/psqlextra
        postgresql: true
        redis: true
    dependencies:
        override:
            - 'pip install -r requirements/test.txt'
    tests:
        before:
            - 'pip install coverage --force-reinstall -U'
        override:
            -
                command: tox
                coverage:
                    file: '.coverage'
                    format: 'py-cc'
