[tool.black]
line-length = 80
exclude = '''
(
  /(
    | .env
    | env
    | venv
    | tests/snapshots
  )/
)
'''

[tool.mypy]
python_version = "3.8"
plugins = ["mypy_django_plugin.main"]
mypy_path = ["stubs", "."]
exclude = "(env|build|dist|migrations)"

[[tool.mypy.overrides]]
module = [
    "psycopg.*"
]
ignore_missing_imports = true

[tool.django-stubs]
django_settings_module = "settings"
